# Custom Language File for Launcher Customizer

[ejs.app]
title = "Frost World Studio"

[ejs.landing]
mediaGitHubURL = "https://frostworld.studio"
mediaTwitterURL = "https://twitter.com/FWStudio_Off"
mediaInstagramURL = "#"
mediaYouTubeURL = "www.youtube.com/@frostworldstudio"
mediaDiscordURL = "https://discord.com/invite/bNE2jBfFWQ"

[ejs.settings]
sourceGithubLink = "https://github.com/GalaxyStudiosFR/FrostWorldLauncher"
supportLink = "https://github.com/GalaxyStudiosFR/FrostWorldLauncher/issues"

[ejs.welcome]
welcomeHeader = "BIENVENUE SUR FROST WORLD STUDIO"
welcomeDescription = "Vous vous apprétez à rejoindre une aventure hors du commun, dans laquelle vous pourrez imaginer votre propre personnage dans un univers créé par notre équipe. Un univers de remplis de monstres que vous pourrez combattre et vous faire des ennemis, ou les épagner et vous faire... des amis ? Vous pourrez également rejoindre un univers dans lequel vous pourriez commencer dans une sorte de prison, remplis de scientifiques et de gardes armés jusqu'au dents, pour réaliser des expériences sur des entités surnaturelles... Qui sait ce qui vous attend sur nos serveurs de jeu ?"
welcomeDescCTA = "Vous êtes à quelques clics de rejoindre l'aventure !"
